#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PROJECT_ROOT="$REPO_ROOT/plan_michael_phelps"
FACTORY_ROOT="$PROJECT_ROOT/design_factory"
DIST_DIR="$FACTORY_ROOT/dist"
OUT_FILE="$DIST_DIR/factory.css"
APP_FILE="$PROJECT_ROOT/app/web/css/factory.css"

mkdir -p "$DIST_DIR"

cat > "$OUT_FILE" <<'HEADER'
/*
  Generated by scripts/build_design_factory_css.sh
  Source: design_factory/packages/*/*.css
*/
HEADER

for part in palette typography motion buttons story progress; do
  SRC="$FACTORY_ROOT/packages/$part/$part.css"
  if [ -f "$SRC" ]; then
    printf "\n/* ---- %s ---- */\n" "$part" >> "$OUT_FILE"
    cat "$SRC" >> "$OUT_FILE"
    printf "\n" >> "$OUT_FILE"
  fi
done

cp "$OUT_FILE" "$APP_FILE"
echo "Design Factory CSS built: $OUT_FILE"
echo "App CSS updated: $APP_FILE"
